-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Vært: localhost:8889
-- Genereringstid: 27. 09 2021 kl. 06:16:46
-- Serverversion: 5.7.32
-- PHP-version: 7.4.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `fresh_tomatoes`
--

-- --------------------------------------------------------

--
-- Struktur-dump for tabellen `movie`
--

CREATE TABLE `movie` (
  `movId` int(10) UNSIGNED NOT NULL,
  `movName` varchar(200) COLLATE utf8_danish_ci NOT NULL,
  `movImage` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `movDescription` text COLLATE utf8_danish_ci,
  `movRating` decimal(2,1) DEFAULT NULL,
  `movDate` date NOT NULL,
  `movGenre` varchar(100) COLLATE utf8_danish_ci NOT NULL,
  `movActors` varchar(200) COLLATE utf8_danish_ci NOT NULL,
  `movAge` int(11) NOT NULL,
  `movBlogDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `movTags` varchar(200) COLLATE utf8_danish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;

--
-- Data dump for tabellen `movie`
--

INSERT INTO `movie` (`movId`, `movName`, `movImage`, `movDescription`, `movRating`, `movDate`, `movGenre`, `movActors`, `movAge`, `movBlogDate`, `movTags`) VALUES
(117, 'Daddy\'s Home 2', 'daddys_home_2_-_plakat.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">I komedien \'Daddy\'s Home 2\' vender Dusty og Brad fra&nbsp;<a style=\"background-color: transparent; color: #4355dd; outline: #000000 none; text-decoration-line: none; transition: color 400ms ease 0s;\" href=\"https://www.kino.dk/film/d/da/daddys-home\">etteren</a>&nbsp;tilbage.&nbsp;</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Far Dusty har f&aring;et det til at fungere med sin tidligere rival, stedfar Brad, og begge har nye familier med stedb&oslash;rn og koner.&nbsp;</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Men da julen st&aring;r for d&oslash;ren, er der alligevel noget der mangler. Derfor inviterer makkerparret deres respektive f&aelig;dre p&aring; bes&oslash;g, for at b&oslash;rnene kan f&aring; &eacute;n stor, samlende h&oslash;jtid med bedstef&aelig;drene.&nbsp;</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Da Dusty og Brads f&aelig;dre dukker op, st&aring;r det klart, hvor forskellige de to er, og snart er en rivalisering om b&oslash;rnenes gunst uundg&aring;elig.&nbsp;</p>', '4.0', '2017-11-23', 'komedie, feelgood, familiefilm', 'Mark Wahlberg, Will Ferrel, Mel Gibson, ', 8, '2021-09-22 19:41:33', 'jul, sjov, familie, '),
(118, '21 Jump Street', '21jumpstreet.jpeg', '\'21 Jump Street\' er en filmatisering af 80er tv-serien af samme navn (på dansk: \'De unge strissere\') med bl.a. Johnny Depp\r\nSchmidt (Jonah Hill) og Jenko (Channing Tatum) var vidt forskellige typer i high school og færdes absolut ikke i de samme kredse. Da de nogle år senere mødes på politiskolen, ender de som bedste venner.\r\nDeres første anholdelse går ikke helt som planlagt, og som konsekvens bliver de sendt tilbage til livet i high school som undercoverbetjente.\r\nDeres mission bliver at infiltrere skolens handel med et nyt og farligt stof, men deres gensyn med skoletiden er en blandet oplevelse for de to venner, der indtager uvante roller. Schmidt får chancen for at være en af de populære, mens Jenko hænger ud med nørderne. Og samtidig har de jo en narko-ring, de skal infiltrere.\r\n', '4.0', '2012-06-14', 'action, komedie', 'Jonah Hill, Channing Tatum, Ice Cube, Brie Larsson', 13, '2021-09-22 19:42:52', '21, jump, street, ice, cube, schmidt, jenko,'),
(119, '22 Jump Street', '22Jump.jpeg', '<p><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Filmen \'22 Jump Street\' handler om de to umodne og upr&oslash;vede politibetjente&nbsp;Schmidt og Jenko, der reddede dagen, da de&nbsp;gik undercover som high school-elever og fandt&nbsp;frem til en mystisk narkobagmand i filmen&nbsp;</span><a style=\"background-color: #ffffff; color: #4355dd; outline: #000000 none; text-decoration-line: none; transition: color 400ms ease 0s; font-family: Kino, sans-serif; font-size: 17px;\" title=\"21 Jump Street\" href=\"https://www.kino.dk/film/2/21/21-jump-street\">21 Jump Street</a><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">. Nu h&oslash;rer&nbsp;high school fortiden til, og tiden er kommet&nbsp;til den n&aelig;ste store opgave, der selvf&oslash;lgelig indeb&aelig;rer,&nbsp;at de unge m&aelig;nd starter p&aring; college.&nbsp;</span><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Problemet er blot, at omgivelserne byder p&aring; en del flere fristelser for makkerparret, der m&oslash;der nye og mere ligesindede venner p&aring; football-holdet og blandt kunstelskerne. Pludseligt m&aring; de to venner tage b&aring;de deres professionelle og private forhold op til overvejelse, mens de fors&oslash;ger at fange endnu en skurk blandt de intetanende elever. Men kan politistyrkens &aelig;ldste teenagere finde frem til en moden l&oslash;sning?&nbsp;</span></p>', '4.0', '2014-06-19', 'action, komedie', 'Jonah Hill, Channing Tatum, Ice Cube, Dave Franco', 13, '2021-09-22 19:44:01', '22, jump, street, ice, cube, schmidt, jenko, jeff, mynameisjeff'),
(120, 'Ternet Ninja 2', 'ternetninja2.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Animationsfilmen \'Ternet Ninja 2\' er forts&aelig;ttelsen Anders Matthesens publikumssucces&nbsp;<a style=\"background-color: transparent; color: #4355dd; outline: #000000 none; text-decoration-line: none; transition: color 400ms ease 0s;\" href=\"https://www.kino.dk/film/t/te/ternet-ninja\">Ternet Ninja</a>, som er baseret p&aring; b&oslash;rnebogen af samme navn.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Da skurken Philip Eberfr&oslash; bliver l&oslash;sladt fra det thailanske f&aelig;ngsel, m&aring; Aske og den ternede ninja finde en m&aring;de at fange ham p&aring;, f&oslash;r han slipper v&aelig;k.&nbsp;</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Derfor rejser Aske, dukken og hele familien til Thailand, hvor et stort eventyr - og Onkel Stewart - venter. P&aring; hjemmefronten k&aelig;mper Aske samtidig med forholdet til Jessica, som m&aring;ske mere er p&aring; udkig efter en \"bad boy\".</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Anders Matthesen er b&aring;de manuskriptforfatter og medinstrukt&oslash;r p&aring; \'Ternet Ninja 2\', hvor han ogs&aring; leverer alle stemmerne, p&aring;n&aelig;r til Aske og Jessica, ligesom at han ogs&aring; igen har lavet en r&aelig;kke helt nye sange til filmens soundtrack.</p>', '5.0', '2021-08-19', 'animation, eventyr', 'Anders Mathessen', 10, '2021-09-22 19:45:05', 'anden, ninja, ternet, sjov, anders, mathessen, '),
(121, 'Ternet Ninja', 'ternetninjaplakat.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Animationsfilmen \'Ternet Ninja\' er en filmatisering af Anders \'Anden\' Matthesens popul&aelig;re b&oslash;rnebog af samme navn.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Filmen f&oslash;lger teenageren Aske, der f&aring;r en Ninja-dukke af sin onkel Stewart, da han vender hjem fra Thailand. Dukken viser sig imidlertidigt at v&aelig;re levende, d&oslash;dens farlig og besat af tanken om retf&aelig;rdighed og blodh&aelig;vn over for manden, som ejer fabrikken, den er lavet p&aring;.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Den ternede ninja hj&aelig;lper Aske med hans problemer, og drengen lover til geng&aelig;ld at hj&aelig;lpe dukken, uden helt at vide, hvad det indeb&aelig;rer. Dukken er fast besluttet p&aring; at f&aring; h&aelig;vn ved at sl&aring; den skuppell&oslash;se direkt&oslash;r ihjel, men Aske insisterer p&aring;, at der er en bedre l&oslash;sning.&nbsp;</p>', '4.0', '2018-12-25', 'animation, eventyr', 'Anders Mathessen', 10, '2021-09-22 19:45:58', 'anden, ninja, ternet, sjov, anders, mathessen, '),
(122, 'Den Unge Zlatan', 'den_unge_zlatan_plakat.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Den svenske dokumentarfilm \'Den unge Zlatan\' handler om fodboldspilleren Zlatan&nbsp;Ibrahimovic&nbsp;med fokus p&aring; hans vej fra ghettoen til ber&oslash;mt fodboldspiller.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Filmen f&oslash;lger karrierens begyndelse med debuten for Malm&ouml; FF i 1999, de problematiske &aring;r i Ajax Amsterdam og frem til det endelige gennembrud i Juventus.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Talentet med de bosniske og kroatiske aner er konstant i konflikt med sine omgivelser, der ser ham som egoistisk og kun interesseret i at pleje sin egen karriere. Samtidig hober forventningerne til ham sig op.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Dokumentaren er med sit fokus p&aring; de unge &aring;r en oprindelseshistorie, og idet instrukt&oslash;rerne havde adgang til Zlatan, f&oslash;r han blev verdenskendt, giver filmen muligvis det mest &aelig;rlige billede af fodboldspillerens vej til stjernestatus.</p>', '5.0', '2016-06-01', 'dokumentar', 'Zlatan Ibrahimovic', 8, '2021-09-22 19:48:39', 'zlatan, kongen, fodbold, sverige, vinder, cool'),
(123, 'Coach Carter', 'plakat-coach-carter_1.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Ken Carter er ikke nogen almindelig tr&aelig;ner. Han vil ikke kun have sine drenge til at vinde basketball-kampe: Han vil ogs&aring; have dem til at tage en eksamen.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Spillerne p&aring; hans hold p&aring; Richmond High School forpligter sig til at holde gennemsnittet, opf&oslash;re sig p&aelig;nt og l&aelig;re at g&aring; med slips. Til geng&aelig;ld l&aelig;rer han dem at spille dr&oslash;mmebasketball.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">I vinteren 1998 g&aring;r det str&aring;lende. Ubesejret i 13 kampe er holdet p&aring; vej til at vinde turneringen og begejstrede for&aelig;ldre og fans fylder b&aelig;nkeraderne til hjemmekampene.</p>\r\n<p style=\"margin: 0px; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Men den 4. januar 1999 s&aelig;tter Coach Carter h&aelig;ngel&aring;s p&aring; gymnastiksalen og n&aelig;gter at tr&aelig;ne spillerne videre &ndash; indtil de har forbedret deres karakterer!</p>', '4.0', '2005-04-29', 'drama', 'Samuel L Jackson, Channing Tatum, ', 15, '2021-09-22 19:51:37', 'basketball, coach, carter, sport, drama, usa, kultur'),
(124, 'Uncut Gems ', 'uncut_gems_plakat.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Filmen \'Uncut Gems\' handler om en karismatisk jueveler fra New York, der er p&aring; udkig efter sin n&aelig;ste store kup.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Han satser alt, men han presses fra alle sider, og m&aring; b&aring;de balancere familie og modstandere, mens han skal udf&oslash;re en n&aelig;rmest umulig opgave.</p>', '4.0', '2019-12-25', 'drama, krimi', 'Adam Sandler', 15, '2021-09-22 19:54:00', 'stoffer, betting, odds, basketball, sport, hanukkah'),
(125, 'Klaus', 'klausplakat_0.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Filmen \'Klaus\' er en animationsfilm med danske stemmer af bl.a. Jonatan Spang, Lars Mikkelsen og Christiane Schaumburg-M&uuml;ller.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Jesper er postakademiets v&aelig;rste studerende, og som straf bliver han udstationeret p&aring; en iskold &oslash; over polarcirklen, hvor de lokale beboere bruger det meste af deres tid p&aring; at bekrige hinanden. Netop som Jesper er ved at give op, m&oslash;der han den lokale l&aelig;rer Alva, som bliver hans ven og allierede. Han m&oslash;der ogs&aring; Klaus, en mystisk t&oslash;mrer, der bor alene i en hytte fyldt med h&aring;ndlavet leget&oslash;j.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Disse venskaber bringer latteren tilbage til Smeerensburg og skaber et milj&oslash; med gener&oslash;se naboer, magisk l&aelig;rdom og omhyggeligt oph&aelig;ngte julesokker p&aring; kaminhylden.</p>\r\n<p>&nbsp;</p>', '4.0', '2019-11-08', 'animation, eventyr, jul,', 'Norm Macdonald, Sergio Pablos, J.K.Simmons, Rashida Jones', 5, '2021-09-22 19:57:31', 'jul, hygge, julemand, sne, gaver, tro'),
(126, 'Last Christmas', 'last_christmas_plakat.png', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Den romantiske julefilm \'Last Christmas\' handler om den unge kvinde Kate, hvis liv er k&oslash;rt ud p&aring; et sidespor.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Kate arbejder for den julebesatte Santa i en hel&aring;rs julebutik, men hun er slet ikke i julestemning denne december, efter hun sidste &aring;r blev alvorligt syg og var t&aelig;t p&aring; at d&oslash;.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Efter mange d&aring;rlige beslutninger og endnu en omgang t&oslash;mmerm&aelig;nd m&oslash;der Kate den positive Tom, som sender hende i en bedre retning, og alt h&aring;b er m&aring;ske alligevel ikke ude for, at julestemningen ogs&aring; kan findes i &aring;r.</p>\r\n<p>&nbsp;</p>', '4.0', '2019-11-14', 'romantik, familiefilm, jul', 'Emilia Clarke, Henry Golding, Peter Mygind', 10, '2021-09-22 20:00:03', 'jul, hygge, khaleesi, tro, faith'),
(127, 'Teorien Om Alting', 'teorien_om_alting_plakat.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Biografien \'Teorien om alting\' er historien om videnskabsmanden Stephen Hawking, hvis teorier om kosmos og kvante-tyngdekraft har gjort ham til en superstjerne inden for fysik.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Filmen tager sin begyndelse, da han som ung mand starter p&aring; det prestigefyldte Cambridge University i 1960erne, hvor han forelsker sig i den kunsthistoriestuderende Jane Wilde. Hawking f&aring;r kort efter konstateret den nervesv&aelig;kkende sygdom Amyotrofisk lateral sklerose, men i kampen mod h&aring;rde odds og dystre forudsigelser fra l&aelig;gerne bliver k&aelig;rligheden deres st&aelig;rkeste v&aring;ben. Samtidig arbejder Hawking p&aring; en banebrydende teori.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">&nbsp;</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">&nbsp;</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">&nbsp;</p>\r\n<p>&nbsp;</p>', '4.0', '2015-02-26', 'drama, romantik', 'Eddie Redmayne, Felicity Jones', 10, '2021-09-22 20:03:06', 'hawkings, science, kloghed, '),
(128, 'Role Models', 'rolemodelsdk_1.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">\'Role Models\' f&oslash;lger Danny og Wheeler, der slipper for f&aelig;ngselstid ved at&nbsp;agere mentorer for b&oslash;rn og unge.<br /><br />Wheeler, der ikke har andet end sprut og piger i hovedet, og hans mavesure kollega Danny, hvis k&aelig;reste lige har sl&aring;et op med ham, er&nbsp;bestemt ikke de mest indlysende rollemodeller.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Ikke overraskende g&aring;r b&oslash;rnene hurtigt Danny og Wheeler p&aring; nerverne, kun overg&aring;et af hvor meget de pisser hinanden af, s&aring; de bliver snart n&aelig;sten indstillet p&aring; at v&aelig;lge f&aelig;ngsel alligevel.&nbsp;</p>', '4.0', '2009-02-27', 'komedie', 'Paul Rudd, Sean William Scott, Elizabeth Banks', 13, '2021-09-22 20:05:18', 'fun, pædagog, skør, energi, rollespil, kiss, venskab'),
(129, 'Evan Almighty', 'evan-almighty_800.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Steve Carell spiller igen den polerede, selvglade nyhedsopl&aelig;ser Evan Baxter fra \'Bruce den alm&aelig;gtige\'. Det er nu hans tur til at blive sendt ud p&aring; en hellig mission af Gud.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Evan er lige blevet valgt til kongressen og sammen med familien, flytter han fra Buffalo til forst&aelig;derne i det nordlige Virginia. Men hans nye liv bliver vendt brat p&aring; hovedet, da Gud (Morgan Freeman) viser sig for ham og beordre ham til at bygge en ark.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Evans noget forbavsede familie kan ikke helt finde ud af, om han har en gevaldig midtvejskrise, eller om han har haft en &aring;benbaring af bibelske dimensioner.</p>', '4.0', '2007-07-27', 'komedie', 'Morgan Freeman, Steve Carrel, John Goodman, Lauren Graham', 8, '2021-09-22 20:07:24', 'noah, dyr, gud, ark, bibel, sjov, tro'),
(130, 'HARRY POTTER OG HALVBLODSPRINSEN', 'half-blood.jpeg', '<p><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">I &rsquo;Harry Potter and the Half-Blood Prince&rsquo; (Harry Potter og Halvblodsprinsen) har Voldemort strammet sit greb om b&aring;de Mugglerne og troldmandsverdenen.&nbsp;</span><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Hogwarts er ikke l&aelig;ngere et sikkert sted at opholde sig, og Harry Potter har mistanke om, at faren ligger indenfor skolens mure.&nbsp;</span><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Dumbledore er dog mere opsat p&aring; at forberede ham p&aring; den endelige kamp, som han ved n&aelig;rmer sig, og sammen fors&oslash;ger de at finde den n&oslash;gle, der kan afsl&oslash;re Voldemorts forsvar. For at g&oslash;re dette rekrutterer Dumbledore sin gamle ven og kollega, levemanden Professor Horace Schnobbevom, som menes at have vitale informationer, der kan bruges mod Voldemort.</span></p>', '5.0', '2009-07-17', 'eventyr', 'Daniel Radcliffe, Emma Watson, Rupert Grint', 10, '2021-09-22 20:09:55', 'magi, hekse, troldmand, eventyr, fantasi, tryllestav'),
(131, 'HARRY POTTER OG FØNIXORDENEN', 'potter5.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">I \'Harry Potter and the Order of the Phoenix\' (Harry Potter og F&oslash;nixordenen) st&aring;r troldmanden over for endnu et semester p&aring; Hogwarts.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Han vender tilbage til sit femte &aring;r p&aring; skolen for heksekunster og trylleri, for at opdage at trolddomsmilj&oslash;et ikke vil erkende Lord Voldemorts tilbagekomst. Samtidig har Ministeren for Magi, Cornelius Fudge, indsat en ny rektor p&aring; Hogwarts, for at eleverne ikke skal h&oslash;re om Voldemorts genopv&aelig;kkelse fra professor Dumbledore.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Eleverne har som altid ogs&aring; f&aring;et en ny professor i Forsvar mod M&oslash;rkets Kr&aelig;fter, og hun er endnu en forhindring for de unge troldm&aelig;nd. Harry, Hermione og Ron danner en hemmelig klub, Dumbledores Army, hvor de og andre elever g&aring;r sammen for at klare m&oslash;rkets kr&aelig;fter.</p>', '4.0', '2007-07-13', 'eventyr', 'Daniel Radcliffe, Emma Watson, Rupert Grint', 10, '2021-09-22 20:11:06', 'ma'),
(132, 'STAR WARS (1977)', 'star_wars_ver2_xlg.jpeg', '<p><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">\'Star Wars\'&nbsp;(Stjernekrigen) er det f&oslash;rste, eller i&nbsp;virkeligheden fjerde,&nbsp;kapitel&nbsp;i George Lucas\' legendariske rumeventyr.</span><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Det galaktiske Imperium med Darth Vader i spidsen har bygget en rumstation kaldet D&oslash;dsstjernen, der har et kraftigt nok v&aring;ben til at &oslash;del&aelig;gge hele planeter. Men en gruppe rebeller k&aelig;mper imod overmagten.</span></p>', '3.0', '1997-09-26', 'eventyr, science fiction', 'Harrison Ford, Mark Hamill, Carrie Fisher, Yoda', 10, '2021-09-22 20:13:42', 'stjernekrig, rummet, lyssværd, planeter, grrrrrrr'),
(133, 'TERKEL I KNIBE', 'terkeliknibeplakat.jpeg', '<p><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Animationsfilmen \'Terkel i knibe\' er baseret p&aring; Anders Matthesens lyttespil af samme navn.</span><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Filmen handler om drengen Terkel, hans ven Jason og de begivenheder, der s&aelig;ttes i gang, da klassen f&aring;r en ny vikar.</span></p>', '3.0', '2004-04-02', 'animation, dansk', 'Anders Mathessen', 13, '2021-09-22 20:15:31', 'anden, jernrør, terkel, jason, sjov, anders, mathessen, fede dorit'),
(134, 'Focus', 'focus_plakat.jpeg', '<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Filmen \'Focus\' handler om den erfarne hustler Nicky, der tager den unge, smukke Jess under sin vinge for at opl&aelig;re hende i svindleriets &aelig;dle kunst.</p>\r\n<p style=\"margin: 0px 0px 1em; padding: 0px; font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Jess har et naturtalent for uset at nappe punge, tasker og kreditkort fra folk og passer derfor perfekt ind i Nickys bande. Men da l&aelig;rermester og elev starter et romantisk forhold, begynder komplikationerne at hobe sig op, og snart m&aring; Nicky beslutte sig for, hvad der er vigtigst for ham.</p>', '4.0', '2015-03-05', 'komedie, thriller', 'Will Smith, Margot Robbie', 13, '2021-09-22 20:17:52', 'odds, betting, cool, lommetyv, '),
(135, 'I Am Legend', 'plakat-i-am-legend.jpeg', 'Science fiction-filmen \'I Am Legend\' handler om den geniale videnskabsmand Robert Neville. Men selv ikke han kunne holde den forf&aelig;rdelige, uhelbredelige og menneskeskabte virus nede, der spredte sig over hele kloden.\r\n<br>\r\nNeville, der &aring;benbart er immun, er nu det sidste overlevende menneske i New York. I tre &aring;r har Neville dagligt sendt radiobeskeder for at komme i kontakt med eventuelle andre overlevende.\r\n<br>\r\n\r\nMen helt alene er han ikke. N&aring;r solen g&aring;r ned, kommer mutanterne frem. Mutanterne er dem, der overlevede virussen &ndash;&nbsp;<em>De Inficerede</em>&nbsp;&ndash; de lurer i skyggerne og overv&aring;ger hver en bev&aelig;gelse fra Neville, mens de venter p&aring;, at han beg&aring;r en fatal fejltagelse...', '4.0', '2005-12-25', 'action, thriller, science fiction', 'Will Smith, Alice Braga', 13, '2021-09-22 20:19:48', 'palle alene i verden, zoombie, hund, monster, kur, modgift'),
(136, 'Iron Man 2', 'plakat_1.jpeg', '<p><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">I&nbsp;\'Iron Man 2\' vender Robert Downey Jr. vender tilbage som milliard&aelig;ren og opfinderen Tony Stark.</span><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">I forts&aelig;ttelsen ved hele verden, at det er Stark, som gemmer sig bag superhelten Iron Mans pansrede jerndragt.</span><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><br style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\" /><span style=\"font-family: Kino, sans-serif; font-size: 17px; background-color: #ffffff;\">Stark er under pres fra regeringen, medierne og offentligheden for at dele teknologien med milit&aelig;ret, men han &oslash;nsker ikke at afsl&oslash;re hemmelighederne bag Iron Mans panser. Han frygter nemlig, at oplysningerne kan havne i de forkerte h&aelig;nder.</span></p>', '3.0', '2010-04-29', 'action', 'Robert Downey JR, Don Cheadle, Gwyneth Paltrow', 13, '2021-09-22 20:32:37', 'superhelt, jernmand, helt, skurk, ');

--
-- Begrænsninger for dumpede tabeller
--

--
-- Indeks for tabel `movie`
--
ALTER TABLE `movie`
  ADD PRIMARY KEY (`movId`);

--
-- Brug ikke AUTO_INCREMENT for slettede tabeller
--

--
-- Tilføj AUTO_INCREMENT i tabel `movie`
--
ALTER TABLE `movie`
  MODIFY `movId` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=137;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
